stages:
  
deploy

deploy:
  stage: deploy
  script:
    
echo "Deploying static site..."
mkdir public               # Create the public directory
cp -r * public             # Copy all files into the public directory
artifacts:
  paths:
public                   # Specify the public directory for deployment
only:
main                       # Run this job only on the main branch